Repository Grupo9-PIV/Key-Vault, pull requests merged in 2025-02, with the labels that each got.

#21 Injeção de dependência com sessão e CRUD de usuários
  backend/src/app.py
  backend/src/database/__init__.py
  backend/src/schemas/user.py
  backend/src/services/__init__.py
  backend/src/services/user_service.py
  backend/tests/conftest.py
  backend/tests/test_users.py
Labels: enhancement

#22 13 features de seguranca
  backend/poetry.lock
  backend/pyproject.toml
  backend/src/app.py
  backend/src/exceptions.py
  backend/src/schemas/__init__.py
  backend/src/schemas/token.py
  backend/src/security/__init__.py
  backend/src/security/auth.py
  backend/src/security/hashing.py
  backend/src/services/user_service.py
  backend/src/settings.py
  backend/tests/conftest.py
  backend/tests/test_models_user.py
  backend/tests/test_security.py
  backend/tests/test_token.py
  backend/tests/test_users.py
Labels: enhancement

#24 Refatoração das rotas
  backend/src/app.py
  backend/src/exceptions/__init__.py
  backend/src/routes/__init__.py
  backend/src/routes/auth.py
  backend/src/routes/users.py
  backend/src/security/auth.py
  backend/src/settings/__init__.py
  backend/src/settings/settings.py
  backend/src/types/__init__.py
  backend/tests/conftest.py
  backend/tests/test_app.py
  backend/tests/test_auth.py
  backend/tests/test_models_audit_log.py
  backend/tests/test_security.py
  backend/tests/test_users.py
Labels: enhancement

#25 Add landing page
  docs/.gitkeep
  docs/images/logo.png
  docs/index.html
  docs/produto.html
  docs/styles.css
Labels: enhancement

#32 Endpoint PATCH de Users
  backend/src/enums/audit_action.py
  backend/src/enums/license_priority.py
  backend/src/enums/license_status.py
  backend/src/enums/license_type.py
  backend/src/enums/request_status.py
  backend/src/enums/user_role.py
  backend/src/routes/users.py
  backend/src/schemas/__init__.py
  backend/src/schemas/user.py
  backend/src/services/user_service.py
  backend/tests/test_users.py
Labels: enhancement

#26 Lynn branch
  README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/KVicon.png
  frontend/public/licencas.png
  frontend/public/logo.png
  frontend/public/notificacoes.png
  frontend/public/renovacoes.png
  frontend/public/sino.png
  frontend/public/usuarios.png
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Initial.jsx
  frontend/src/pages/LicenseDetail.jsx
  frontend/src/pages/LicenseList.jsx
  frontend/src/pages/Notifications.jsx
  frontend/src/pages/RenewalDetail.jsx
  frontend/src/pages/Renewals.jsx
  frontend/src/pages/UsersDetail.jsx
  frontend/src/pages/UsersList.tsx
  frontend/src/routes.jsx
  frontend/src/styles/LicenseList.css
  frontend/src/styles/style.css
  frontend/yarn.lock
  package-lock.json
  package.json
Labels: enhancement, good first issue

#35 Melhorias no README
  README.md
  docs/images/tech-stack.png
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes.jsx
  frontend/yarn.lock
  package-lock.json
  package.json
Labels: enhancement

#42 Containerização do projeto
  .dockerignore
  README.md
  backend/Dockerfile
  backend/Makefile
  backend/README.md
  backend/entrypoint.sh
  backend/poetry.lock
  backend/pyproject.toml
  backend/src/exceptions/__init__.py
  backend/src/exceptions/license_exceptions.py
  backend/src/routes/license_routes.py
  backend/src/schemas/license.py
  backend/src/services/license_service.py
  backend/src/settings/settings.py
  backend/tests/conftest.py
  backend/tests/test_models_user.py
  deploy/compose.yaml
  docs/images/mer.png
Labels: enhancement

#41 Documentação do frontend + dependências de desenvolvimento
  .gitignore
  README.md
  frontend/.prettierrc.json
  frontend/README.md
  frontend/jest.config.js
  frontend/jest.setup.js
  frontend/package.json
  frontend/yarn.lock
Labels: documentation

#44 CI Básico
  .github/workflows/pytest.yml
  README.md
  backend/src/database/__init__.py
Labels: enhancement

#45 Refatoração do endpoint auth
  backend/src/exceptions/__init__.py
  backend/src/exceptions/auth.py
  backend/src/exceptions/base.py
  backend/src/exceptions/users.py
  backend/src/routes/auth.py
  backend/src/services/__init__.py
  backend/src/services/auth_service.py
Labels: enhancement

#47 Aplicação containerizada
  .github/workflows/pytest.yml
  backend/src/app.py
  backend/src/settings/settings.py
  deploy/compose.yaml
  frontend/index.html
  frontend/public/assets/KVicon.png
  frontend/public/assets/licencas.png
  frontend/public/assets/logo.png
  frontend/public/assets/notificacoes.png
  frontend/public/assets/react.svg
  frontend/public/assets/renovacoes.png
  frontend/public/assets/sino.png
  frontend/public/assets/usuarios.png
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Initial.jsx
  frontend/src/pages/LicenseDetail.jsx
  frontend/src/pages/LicenseList.jsx
  frontend/src/pages/Notifications.jsx
  frontend/src/pages/RenewalDetail.jsx
  frontend/src/pages/Renewals.jsx
  frontend/src/pages/UsersDetail.jsx
  frontend/src/pages/UsersList.tsx
  frontend/src/routes.jsx
  frontend/src/styles/style.css
  nginx/Dockerfile
  nginx/nginx.conf
Labels: enhancement
