Repository Grupo9-PIV/Key-Vault, pull requests merged in 2025-03, with the labels that each got.

#50 Integração frontend-backend
  .dockerignore
  .gitignore
  README.md
  backend/README.md
  deploy/compose.yaml
  frontend/README.md
  frontend/src/App.jsx
  frontend/src/api.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/pages/Initial.jsx
  frontend/vite.config.js
  nginx/Dockerfile
Labels: bug, enhancement

#52 Mais ajustes
  README.md
  backend/src/app.py
  backend/src/schemas/__init__.py
  backend/src/schemas/message.py
  backend/tests/test_app.py
  deploy/compose.yaml
  frontend/index.html
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/api.jsx
  frontend/src/api/index.jsx
  frontend/src/api/interceptors.jsx
  frontend/src/api/tokenService.jsx
  frontend/yarn.lock
Labels: enhancement

#49 Testes de rota criados
  backend/src/exceptions/__init__.py
  backend/src/exceptions/license_exceptions.py
  backend/src/routes/__init__.py
  backend/src/routes/license_routes.py
  backend/src/schemas/license.py
  backend/src/services/license_service.py
  backend/tests/conftest.py
  backend/tests/test_licenses.py
Labels: enhancement

#60 Adiciona validação de senhas
  backend/migrations/versions/65ca3ec333da_create_users_table.py
  backend/src/models/user.py
  backend/src/schemas/license.py
  backend/src/schemas/token.py
  backend/src/schemas/user.py
  backend/src/services/auth_service.py
  backend/src/services/license_service.py
  backend/src/services/user_service.py
  backend/src/types/__init__.py
  backend/src/types/password.py
  backend/tests/conftest.py
  backend/tests/factory/__init__.py
  backend/tests/factory/faker.py
  backend/tests/factory/license_factory.py
  backend/tests/factory/user_factory.py
  backend/tests/test_licenses.py
  backend/tests/test_models_license.py
  backend/tests/test_models_user.py
  backend/tests/test_users.py
  backend/tests/utils/__init__.py
Labels: bug, enhancement

#63 Renewal Requests
  backend/src/exceptions/__init__.py
  backend/src/exceptions/license.py
  backend/src/exceptions/renewal_request.py
  backend/src/models/renewal_request.py
  backend/src/routes/__init__.py
  backend/src/routes/auth.py
  backend/src/routes/renewal_requests.py
  backend/src/routes/users.py
  backend/src/schemas/__init__.py
  backend/src/schemas/license.py
  backend/src/schemas/renewal_request.py
  backend/src/schemas/user.py
  backend/src/services/__init__.py
  backend/src/services/renewal_requests.py
  backend/src/types/__init__.py
  backend/src/types/dependencies.py
  backend/src/types/filters.py
  backend/src/types/password.py
  backend/tests/conftest.py
  backend/tests/factory/license_factory.py
  backend/tests/factory/user_factory.py
  backend/tests/test_models_request.py
Labels: enhancement

#62 Lynn create user style
  frontend/src/components/Header.jsx
  frontend/src/pages/ChangePassword.jsx
  frontend/src/pages/CreateUser.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/MyAccount.jsx
  frontend/src/pages/UsersList.tsx
  frontend/src/routes.jsx
  frontend/src/styles/style.css
Labels: enhancement

#64 Security patch
  backend/poetry.lock
  backend/pyproject.toml
  backend/src/security/auth.py
  backend/tests/test_licenses.py
Labels: dependencies

#57 38 adicionar link do repositório na landing page
  docs/images/WhatsApp Image 2025-03-09 at 19.30.43.jpeg
  docs/images/github.png
  docs/index.html
  docs/produto.html
  docs/styles.css
Labels: documentation

#68 Fix landing page logo
  docs/images/logo-transparent.png
  docs/index.html
Labels: bug
